### ISSUE TITLE
connection_error_strategy not working for ingore

### ISSUE THREAD

**Issue by petr-balogh** [rhevm-qe-automation/pytest_jira#143]
Even though we have :
connection_error_strategy

As part of our config file `/etc/jira.cfg`:

```
[DEFAULT]
url = https://issues.redhat.com
token = jira_token
run_test_case = False
connection_error_strategy = ignore
docs_search=False
```

One day we saw a lot of executions just failed with no test running because of internal pytest error:

```
2024-12-14 11:44:38  INTERNALERROR> Traceback (most recent call last):
2024-12-14 11:44:38  INTERNALERROR>   File "/home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/venv/lib64/python3.9/site-packages/_pytest/main.py", line 269, in wrap_session
2024-12-14 11:44:38  INTERNALERROR>     session.exitstatus = doit(config, session) or 0
2024-12-14 11:44:38  INTERNALERROR>   File "/home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/venv/lib64/python3.9/site-packages/_pytest/main.py", line 322, in _main
2024-12-14 11:44:38  INTERNALERROR>     config.hook.pytest_collection(session=session)
2024-12-14 11:44:38  INTERNALERROR>   File "/home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/venv/lib64/python3.9/site-packages/pluggy/_hooks.py", line 513, in __call__
2024-12-14 11:44:38  INTERNALERROR>     return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
2024-12-14 11:44:38  INTERNALERROR>   File "/home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/venv/lib64/python3.9/site-packages/pluggy/_manager.py", line 120, in _hookexec
2024-12-14 11:44:38  INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
2024-12-14 11:44:38  INTERNALERROR>   File "/home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/venv/lib64/python3.9/site-packages/pluggy/_callers.py", line 182, in _multicall
2024-12-14 11:44:38  INTERNALERROR>     return outcome.get_result()
2024-12-14 11:44:38  INTERNALERROR>   File "/home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/venv/lib64/python3.9/site-packages/pluggy/_result.py", line 100, in get_result
2024-12-14 11:44:38  INTERNALERROR>     raise exc.with_traceback(exc.__traceback__)
2024-12-14 11:44:38  INTERNALERROR>   File "/home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/venv/lib64/python3.9/site-packages/pluggy/_callers.py", line 103, in _multicall
2024-12-14 11:44:38  INTERNALERROR>     res = hook_impl.function(*args)
2024-12-14 11:44:38  INTERNALERROR>   File "/home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/venv/lib64/python3.9/site-packages/_pytest/main.py", line 333, in pytest_collection
2024-12-14 11:44:38  INTERNALERROR>     session.perform_collect()
2024-12-14 11:44:38  INTERNALERROR>   File "/home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/venv/lib64/python3.9/site-packages/_pytest/main.py", line 637, in perform_collect
2024-12-14 11:44:38  INTERNALERROR>     hook.pytest_collection_modifyitems(
2024-12-14 11:44:38  INTERNALERROR>   File "/home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/venv/lib64/python3.9/site-packages/pluggy/_hooks.py", line 513, in __call__
2024-12-14 11:44:38  INTERNALERROR>     return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
2024-12-14 11:44:38  INTERNALERROR>   File "/home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/venv/lib64/python3.9/site-packages/pluggy/_manager.py", line 120, in _hookexec
2024-12-14 11:44:38  INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
2024-12-14 11:44:38  INTERNALERROR>   File "/home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/venv/lib64/python3.9/site-packages/pluggy/_callers.py", line 182, in _multicall
2024-12-14 11:44:38  INTERNALERROR>     return outcome.get_result()
2024-12-14 11:44:38  INTERNALERROR>   File "/home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/venv/lib64/python3.9/site-packages/pluggy/_result.py", line 100, in get_result
2024-12-14 11:44:38  INTERNALERROR>     raise exc.with_traceback(exc.__traceback__)
2024-12-14 11:44:38  INTERNALERROR>   File "/home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/venv/lib64/python3.9/site-packages/pluggy/_callers.py", line 103, in _multicall
2024-12-14 11:44:38  INTERNALERROR>     res = hook_impl.function(*args)
2024-12-14 11:44:38  INTERNALERROR>   File "/home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/venv/lib64/python3.9/site-packages/pytest_jira.py", line 127, in pytest_collection_modifyitems
2024-12-14 11:44:38  INTERNALERROR>     if not self.is_issue_resolved(issue_id):
2024-12-14 11:44:38  INTERNALERROR>   File "/home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/venv/lib64/python3.9/site-packages/pytest_jira.py", line 80, in is_issue_resolved
2024-12-14 11:44:38  INTERNALERROR>     self.issue_cache[issue_id] = self.conn.get_issue(
2024-12-14 11:44:38  INTERNALERROR>   File "/home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/venv/lib64/python3.9/site-packages/decorator.py", line 232, in fun
2024-12-14 11:44:38  INTERNALERROR>     return caller(func, *(extras + args), **kw)
2024-12-14 11:44:38  INTERNALERROR>   File "/home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/venv/lib64/python3.9/site-packages/retry/api.py", line 90, in retry_decorator
2024-12-14 11:44:38  INTERNALERROR>     return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter,
2024-12-14 11:44:38  INTERNALERROR>   File "/home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/venv/lib64/python3.9/site-packages/retry/api.py", line 35, in __retry_internal
2024-12-14 11:44:38  INTERNALERROR>     return f()
2024-12-14 11:44:38  INTERNALERROR>   File "/home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/venv/lib64/python3.9/site-packages/pytest_jira.py", line 258, in get_issue
2024-12-14 11:44:38  INTERNALERROR>     self.check_connection()
2024-12-14 11:44:38  INTERNALERROR>   File "/home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/venv/lib64/python3.9/site-packages/pytest_jira.py", line 235, in check_connection
2024-12-14 11:44:38  INTERNALERROR>     r = self._jira_request(
2024-12-14 11:44:38  INTERNALERROR>   File "/home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/venv/lib64/python3.9/site-packages/pytest_jira.py", line 229, in _jira_request
2024-12-14 11:44:38  INTERNALERROR>     rsp.raise_for_status()
2024-12-14 11:44:38  INTERNALERROR>   File "/home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/venv/lib64/python3.9/site-packages/requests/models.py", line 1024, in raise_for_status
2024-12-14 11:44:38  INTERNALERROR>     raise HTTPError(http_error_msg, response=self)
2024-12-14 11:44:38  INTERNALERROR> requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: https://issues.redhat.com/rest/api/2/mypermissions?permissions=BROWSE_PROJECTS
```

**Comment by lukas-bednar** [comment]
try  to use 
```
error_strategy = ignore
```
